name: launch_review
description: A Flutter plugin to assist in leaving user reviews/ratings in Google Play Store and Apple App Store.
version: 2.0.0
author: Purusothaman Ramanujam <purushoth.r@gmail.com>
homepage: https://github.com/purus/launch_review/

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.iyaffle.launchreview
    pluginClass: LaunchReviewPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"    
