name: store_redirect
description: A Flutter plugin to redirect users to an app page in Google Play Store and Apple App Store.
version: 2.0.1
author: Daniel Dallos <flutter@danieldallos.com>
homepage: https://github.com/Danesz/store_redirect

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.danieldallos.storeredirect
        pluginClass: StoreRedirectPlugin
      ios:
        pluginClass: StoreRedirectPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"